### PR TITLE
Made the repository not goofy :3

### PR DESCRIPTION
**Pull request by pparaxan**
you're too silly

### CODE REVIEW

**Comment by a-catgirl-dev** [comment]
No. fuck mv3. Google sucks

**Comment by a-catgirl-dev** [comment]
/j hehe had to give you a heart attack

**Comment by pparaxan** [comment]
> /j hehe had to give you a heart attack

brother in chr-

**Comment by a-catgirl-dev** [comment]
WAIT NO ANYTHING BUT CHROME-

**Comment by pparaxan** [comment]
> WAIT NO ANYTHING BUT CHROME-

i didn't even change the src to add chrome support, **you** yourself added it

**Comment by pparaxan** [comment]
dunno if it's by mistake, but it's really funny

**Comment by a-catgirl-dev** [comment]
> > WAIT NO ANYTHING BUT CHROME-
> 
> i didn't even change the src to add chrome support, **you** yourself added it

well no, Firefox extensions are pretty much the same as chrome extensions, by design

**Comment by pparaxan** [comment]
> Firefox extensions are pretty much the same as chrome extensions, by design

oh, :skull:

**Comment by a-catgirl-dev** [comment]
can you bump ver to 1.3 or something lmao

**Comment by a-catgirl-dev** [comment]
(trying my best to delay merging)

**Comment by pparaxan** [comment]
> can you bump ver to 1.3 or something lmao

bru
even so why 1.3, you're at version 1.0.2.4
_did bro forgor which version he's on?_

**Comment by a-catgirl-dev** [comment]
1.1*

**Comment by a-catgirl-dev** [comment]
god damn I have severe dementia

**Comment by pparaxan** [comment]
> god damn I have severe dementia

lmaoo

**Comment by pparaxan** [comment]
'kay, push or no catgirls forever

**Comment by a-catgirl-dev** [comment]
welp, I've lost

**Comment by a-catgirl-dev** [comment]
you are the worst

**Comment by pparaxan** [comment]
> you are the worst

:yippee:

**Pull request merged**
